name: Create release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
permissions:
  contents: write
  actions: write
jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, '[skip-release]')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: install autotag binary
        run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin

      - name: create release
        run: |-
          TAG=$(autotag)
          git push origin v$TAG
          gh release create v$TAG --title "v$TAG" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

